baseURL: "https://axthauvin.onrender.com/"
languageCode: fr
title: Axel Thauvin
theme: "hugo-PaperMod"

defaultContentLanguage: fr
languages:
  fr:
      title: Axel Thauvin
      weight: 1
  en: 
      weight: 2

params:
  
    homeInfoParams:
        Title: Je suis Axel Thauvin,
        Subtitle: passionné d'informatique et de programmation.
        Content: Ici je posterai [***mes projets***](/projets), ainsi que mes différentes offres de [***cours en ligne***](https://axthauvin.github.io/Cours%20en%20ligne.html)
         
  
    socialIcons:
            - name: "github"
              url: "https://github.com/Axthauvin"
            - name: "twitter"
              url: "https://twitter.com/axthauvin"
            - name: "youtube"
              url: "https://www.youtube.com/channel/UCF6zpti-ice10f9RInxHyFA"
    
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    
    editPost:
          URL: "https://github.com/Axthauvin/site-hugo/blob/main/content"
          Text: "Proposer des modifications" # edit text
          appendFilePath: true # to append file path to Edit link
    
    ShowCodeCopyButtons: true
    ShowReadingTime: true
    linkFullImages: true
    ShowReadingTime: true
    


    

menu:
    main:
        - identifier: search
          name: Rechercher
          url: /search/
          weight: 10
        
        - identifier: Curriculum vitæ
          name: Curriculum vitæ
          url: /cv/
          weight: 20
        
        - identifier: cours
          name: Mes cours
          url: "https://axthauvin.github.io/Cours%20en%20ligne.html"
          weight: 30


outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
